import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer";
import { CartProvider } from "@/context/CartContext"; // Import it
import { Toaster } from "sonner"; // 👈 Import Sonner

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.jsdelivr.net/npm/eruda"></script>
<script>eruda.init();</script>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
        <Header/>
        <Toaster />
       <main className="max-w-lg mx-auto px-4">
          {children}
       </main>
       <Footer />
       </CartProvider>
      </body>
    </html>
  );
}
